keys:
- id: user1
  port: 8641
  cipher: chacha20-ietf-poly1305
  secret: Secret1
- id: user2
  port: 8641
  cipher: chacha20-ietf-poly1305
  secret: Secret2
- id: user3
  port: 8641
  cipher: chacha20-ietf-poly1305
  secret: Secret3
